# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

more_treno = [
	#Treni sud->nord
	{
	:id => 1000,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '5:',
	:hf1 => '6:',
	:hf2 => '7:',
	:hf3 => '8:',
	:hf4 => '9:',
	:hf5 => '10:'
	},
	{
	:id => 1002,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '7:',
	:hf1 => '8:',
	:hf2 => '9:',
	:hf3 => '10:',
	:hf4 => '11:',
	:hf5 => '12:'
	},
	{
	:id => 1004,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '9:',
	:hf1 => '10:',
	:hf2 => '11:',
	:hf3 => '12:',
	:hf4 => '13:',
	:hf5 => '14:'
	},
	{
	:id => 1006,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '11:',
	:hf1 => '12:',
	:hf2 => '13:',
	:hf3 => '14:',
	:hf4 => '15:',
	:hf5 => '16:'
	},
	{
	:id => 1008,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '13:',
	:hf1 => '14:',
	:hf2 => '15:',
	:hf3 => '16:',
	:hf4 => '17:',
	:hf5 => '18:'
	},
	{
	:id => 1010,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '15:',
	:hf1 => '16:',
	:hf2 => '17:',
	:hf3 => '18:',
	:hf4 => '19:',
	:hf5 => '20:'
	},
	{
	:id => 1012,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '17:',
	:hf1 => '18:',
	:hf2 => '19:',
	:hf3 => '20:',
	:hf4 => '21:',
	:hf5 => '22:'
	},	
	{
	:id => 1014,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => 'Milano Centrale',
	:f5 => 'Torino Porta Nuova',
	:hf0 => '19:',
	:hf1 => '20:',
	:hf2 => '21:',
	:hf3 => '22:',
	:hf4 => '23:',
	:hf5 => '23:59'
	},

	#/*Treni sud->nord - Venezia
	{
	:id => 1050,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '6:',
	:hf1 => '7:',
	:hf2 => '8:',
	:hf3 => '9:',
	:hf4 => nil,
	:hf5 => '11:'
	},
	{
	:id => 1052,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '8:',
	:hf1 => '9:',
	:hf2 => '10:',
	:hf3 => '11:',
	:hf4 => nil,
	:hf5 => '13:'
	},
	{
	:id => 1054,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '10:',
	:hf1 => '11:',
	:hf2 => '12:',
	:hf3 => '13:',
	:hf4 => nil,
	:hf5 => '15:'
	},
	{
	:id => 1056,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '12:',
	:hf1 => '13:',
	:hf2 => '14:',
	:hf3 => '15:',
	:hf4 => nil,
	:hf5 => '17:'
	},
	{
	:id => 1058,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '14:',
	:hf1 => '15:',
	:hf2 => '16:',
	:hf3 => '17:',
	:hf4 => nil,
	:hf5 => '19:'
	},
	{
	:id => 1060,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '16:',
	:hf1 => '17:',
	:hf2 => '18:',
	:hf3 => '19:',
	:hf4 => nil,
	:hf5 => '21:'
	},
	{
	:id => 1062,
	:f0 => 'Napoli Centrale',
	:f1 => 'Roma Termini',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Bologna Centrale',
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '18:',
	:hf1 => '19:',
	:hf2 => '20:',
	:hf3 => '21:',
	:hf4 => nil,
	:hf5 => '23:'
	},

	#Treni nord->sud
	{
	:id => 1001,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '5:',
	:hf1 => '6:',
	:hf2 => '7:',
	:hf3 => '8:',
	:hf4 => '9:',
	:hf5 => '10:'
	},
	{
	:id => 1003,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '7:',
	:hf1 => '8:',
	:hf2 => '9:',
	:hf3 => '10:',
	:hf4 => '11:',
	:hf5 => '12:'
	},
	{
	:id => 1005,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '9:',
	:hf1 => '10:',
	:hf2 => '11:',
	:hf3 => '12:',
	:hf4 => '13:',
	:hf5 => '14:'
	},
	{
	:id => 1007,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '11:',
	:hf1 => '12:',
	:hf2 => '13:',
	:hf3 => '14:',
	:hf4 => '15:',
	:hf5 => '16:'
	},
	{
	:id => 1009,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '13:',
	:hf1 => '14:',
	:hf2 => '15:',
	:hf3 => '16:',
	:hf4 => '17:',
	:hf5 => '18:'
	},
	{
	:id => 1011,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '15:',
	:hf1 => '16:',
	:hf2 => '17:',
	:hf3 => '18:',
	:hf4 => '19:',
	:hf5 => '20:'
	},
	{
	:id => 1013,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '17:',
	:hf1 => '18:',
	:hf2 => '19:',
	:hf3 => '20:',
	:hf4 => '21:',
	:hf5 => '22:'
	},
	{
	:id => 1015,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => 'Bologna Centrale',
	:f3 => 'Firenze Santa Maria Novella',
	:f4 => 'Roma Termini',
	:f5 => 'Napoli Centrale',
	:hf0 => '19:',
	:hf1 => '20:',
	:hf2 => '21:',
	:hf3 => '22:',
	:hf4 => '23:',
	:hf5 => '23:59'
	},

	#Treni nord->sud - Venezia
	{
	:id => 1051,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Bologna Centrale',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Roma Termini',
	:f4 => nil,
	:f5 => 'Napoli Centrale',
	:hf0 => '6:',
	:hf1 => '8:',
	:hf2 => '9:',
	:hf3 => '10:',
	:hf4 => nil,
	:hf5 => '11:'
	},
	{
	:id => 1053,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Bologna Centrale',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Roma Termini',
	:f4 => nil,
	:f5 => 'Napoli Centrale',
	:hf0 => '8:',
	:hf1 => '10:',
	:hf2 => '11:',
	:hf3 => '12:',
	:hf4 => nil,
	:hf5 => '13:'
	},
	{
	:id => 1055,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Bologna Centrale',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Roma Termini',
	:f4 => nil,
	:f5 => 'Napoli Centrale',
	:hf0 => '10:',
	:hf1 => '12:',
	:hf2 => '13:',
	:hf3 => '14:',
	:hf4 => nil,
	:hf5 => '15:'
	},
	{
	:id => 1057,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Bologna Centrale',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Roma Termini',
	:f4 => nil,
	:f5 => 'Napoli Centrale',
	:hf0 => '12:',
	:hf1 => '14:',
	:hf2 => '15:',
	:hf3 => '16:',
	:hf4 => nil,
	:hf5 => '17:'
	},
	{
	:id => 1059,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Bologna Centrale',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Roma Termini',
	:f4 => nil,
	:f5 => 'Napoli Centrale',
	:hf0 => '14:',
	:hf1 => '16:',
	:hf2 => '17:',
	:hf3 => '18:',
	:hf4 => nil,
	:hf5 => '19:'
	},
	{
	:id => 1061,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Bologna Centrale',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Roma Termini',
	:f4 => nil,
	:f5 => 'Napoli Centrale',
	:hf0 => '16:',
	:hf1 => '18:',
	:hf2 => '19:',
	:hf3 => '20:',
	:hf4 => nil,
	:hf5 => '21:'
	},
	{
	:id => 1063,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Bologna Centrale',
	:f2 => 'Firenze Santa Maria Novella',
	:f3 => 'Roma Termini',
	:f4 => nil,
	:f5 => 'Napoli Centrale',
	:hf0 => '18:',
	:hf1 => '20:',
	:hf2 => '21:',
	:hf3 => '22:',
	:hf4 => nil,
	:hf5 => '23:'
	},

	#Treni ovest->est
	{
	:id => 1100,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '6:',
	:hf1 => '7:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '9:'
	},
	{
	:id => 1102,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '8:',
	:hf1 => '9:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '11:'
	},
	{
	:id => 1104,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '10:',
	:hf1 => '11:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '13:'
	},
	{
	:id => 1106,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '12:',
	:hf1 => '13:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '15:'
	},
	{
	:id => 1108,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '14:',
	:hf1 => '15:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '17:'
	},
	{
	:id => 1110,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '16:',
	:hf1 => '17:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '19:'
	},
	{
	:id => 1112,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '18:',
	:hf1 => '19:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '21:'
	},
	{
	:id => 1114,
	:f0 => 'Torino Porta Nuova',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Venezia Santa Lucia',
	:hf0 => '20:',
	:hf1 => '21:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '23:'
	},

	#Treni est->ovest
	{
	:id => 1101,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '6:',
	:hf1 => '8:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '9:'
	},
	{
	:id => 1103,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '8:',
	:hf1 => '10:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '11:'
	},
	{
	:id => 1105,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '10:',
	:hf1 => '12:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '13:'
	},
	{
	:id => 1107,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '12:',
	:hf1 => '14:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '15:'
	},
	{
	:id => 1109,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '14:',
	:hf1 => '16:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '17:'
	},
	{
	:id => 1111,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '16:',
	:hf1 => '18:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '19:'
	},
	{
	:id => 1113,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '18:',
	:hf1 => '20:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '21:'
	},
	{
	:id => 1115,
	:f0 => 'Venezia Santa Lucia',
	:f1 => 'Milano Centrale',
	:f2 => nil,
	:f3 => nil,
	:f4 => nil,
	:f5 => 'Torino Porta Nuova',
	:hf0 => '20:',
	:hf1 => '22:',
	:hf2 => nil,
	:hf3 => nil,
	:hf4 => nil,
	:hf5 => '23:'
	}
]
more_treno.each do |treno|
	Treno.create(treno)
end
